mutation InsertJobs($jobs: [jobs_insert_input]!) {
  insert_jobs(objects: $jobs) {
    returning {
      id
      name
    }
  }
}
{
  "jobs": [
    {"name":"Software Developer"},
    {"name":"Developer Advocate"},
    {"name":"Associate Software Developer"},
    {"name":"Web Designer"},
    {"name":"Team Leader"},
    {"name":"System Designer"}
  ]
}

mutation MyMutation {
  delete_jobs(where: {id: {_eq: "c32c36ac-51c6-4616-94e1-d335fbcaeb98"}}) {
    affected_rows
  }
}
